import React, { useState } from 'react';
import { Menu, X, Globe, Sparkles, FolderOpen } from 'lucide-react';
import SocialLinks from './SocialLinks';

interface HeaderProps {
  onToggleSidebar?: () => void;
}

const Header = ({ onToggleSidebar }: HeaderProps) => {
  const [isMenuOpen, setIsMenuOpen] = useState(false);

  return (
    <header className="border-b border-slate-800 bg-slate-900/95 backdrop-blur-sm sticky top-0 z-50">
      <div className="px-6 py-5 flex items-center justify-between">
        <div className="flex items-center space-x-4">
          <span
            className="text-blue-400 text-4xl animate-pulse drop-shadow-lg"
            role="img"
            aria-label="crystal ball"
            style={{ filter: 'drop-shadow(0 0 12px #3B82F6)' }}
          >
            🔮
          </span>
          <div>
            <h1
              className="text-xl font-semibold bg-gradient-to-r from-white via-blue-400 to-purple-400 bg-clip-text text-transparent tracking-tight animate-gradient-x"
              style={{
                backgroundSize: '200% 200%',
                animation: 'gradient-x 3s ease-in-out infinite'
              }}
            >
              LouAI
            </h1>
            <p className="text-sm text-slate-400 hidden sm:block">
              Custom web apps generated by AI, using{' '}
              <a href="https://v0.dev" className="text-blue-400 hover:text-blue-300">V0.dev</a>
            </p>
          </div>
          <style>
            {`
              @keyframes gradient-x {
                0%, 100% { background-position: 0% 50%; }
                50% { background-position: 100% 50%; }
              }
              .animate-spin-slow {
                animation: spin 3s linear infinite;
              }
              @keyframes spin {
                100% { transform: rotate(360deg); }
              }
            `}
          </style>
        </div>
        
        <div className="flex items-center space-x-6">
          {/* Projects Button */}
          {onToggleSidebar && (
            <button
              onClick={onToggleSidebar}
              className="flex items-center space-x-2 px-4 py-2 bg-slate-800 hover:bg-slate-700 text-slate-300 hover:text-white rounded-lg transition-colors"
            >
              <FolderOpen size={18} />
              <span className="hidden sm:inline">Projects</span>
            </button>
          )}

          {/* Desktop Social Links */}
          <div className="hidden md:flex">
            <SocialLinks />
          </div>

          {/* Mobile menu button */}
          <button
            className="md:hidden text-slate-300 hover:text-white transition-colors"
            onClick={() => setIsMenuOpen(!isMenuOpen)}
          >
            {isMenuOpen ? <X size={24} /> : <Menu size={24} />}
          </button>
        </div>
      </div>

      {/* Mobile Navigation */}
      {isMenuOpen && (
        <div className="md:hidden bg-slate-900/95 backdrop-blur-xl border-t border-slate-800">
          <div className="px-6 py-4">
            <div className="flex items-center justify-center">
              <SocialLinks />
            </div>
          </div>
        </div>
      )}
    </header>
  );
};

export default Header;